# Generated by Django 3.0.5 on 2020-05-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmewod', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder/'),
        ),
    ]
