# Generated by Django 3.0.5 on 2020-05-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmewod', '0005_auto_20200503_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_URL',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/event_logos/'),
        ),
    ]
