# Generated by Django 3.0.7 on 2020-06-23 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('price', models.CharField(max_length=10)),
                ('short_Description', models.TextField()),
                ('organizer', models.CharField(max_length=20)),
                ('event_URL', models.URLField(default='')),
                ('event_Logo', models.ImageField(blank=True, null=True, upload_to='checkmewod/static/media/images/event_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='VideoSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField(null=True)),
                ('video_file', models.FileField(null=True, upload_to='checkmewod/static/media/videos/uploaded_files/', verbose_name='')),
                ('exercise_in_video', models.TextField(null=True)),
                ('number_reps', models.TextField(null=True)),
                ('number_correct_reps', models.TextField(null=True)),
                ('number_incorrect_reps', models.TextField(null=True)),
                ('video_status', models.TextField(null=True)),
                ('frames_per_rep', models.TextField(null=True)),
                ('user_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
