# Generated by Django 3.0.5 on 2020-05-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmewod', '0005_auto_20200501_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosubmission',
            name='video_id',
            field=models.TextField(null=True),
        ),
    ]
