# Generated by Django 3.0.5 on 2020-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmewod', '0006_videosubmission_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='logo',
        ),
        migrations.AddField(
            model_name='videosubmission',
            name='frames_per_rep',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='video_file',
            field=models.FileField(null=True, upload_to='checkmewod/static/uploaded_files/', verbose_name=''),
        ),
    ]
