# Generated by Django 3.0.5 on 2020-05-03 20:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkmewod', '0007_auto_20200503_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
