# Generated by Django 3.0.5 on 2020-05-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkmewod', '0008_auto_20200503_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/event_logos/'),
        ),
        migrations.AlterField(
            model_name='videosubmission',
            name='video_file',
            field=models.FileField(null=True, upload_to='media/videos/uploaded_files/', verbose_name=''),
        ),
    ]
