# Generated by Django 3.0.5 on 2020-06-07 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkmewod', '0010_auto_20200504_1058'),
        ('checkmewod', '0009_event'),
    ]

    operations = [
    ]
